In [2]:
import pandas as pd

In [3]:
d = {
    'roll':[1,2,3,4,5,6,7,8,9,10],
    'name':['Ajay', 'Amit', 'Arun', 'Anisha', 'Abhay','Ram', 'Sham',
           'Prince', 'Jatin', 'Arshnoor'],
    'maths':[78,87,65,90,98,87,89,56,90,94],
    'physics':[56,87,76,98,95,56,45,78,90,91],
    'chemistry':[90,99,86,89,56,67,73,88,38,40],
    'biology':[58,97,76,58,75,86,35,77,97,41],
}
df = pd.DataFrame(d)
df

   roll      name  maths  physics  chemistry  biology
0     1      Ajay     78       56         90       58
1     2      Amit     87       87         99       97
2     3      Arun     65       76         86       76
3     4    Anisha     90       98         89       58
4     5     Abhay     98       95         56       75
5     6       Ram     87       56         67       86
6     7      Sham     89       45         73       35
7     8    Prince     56       78         88       77
8     9     Jatin     90       90         38       97
9    10  Arshnoor     94       91         40       41

In [4]:
f1 = df['maths'] > 90
f2 = df['physics'] > 90

In [5]:
print(f1)
print(f2)

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7    False
8    False
9     True
Name: maths, dtype: bool
0    False
1    False
2    False
3     True
4     True
5    False
6    False
7    False
8    False
9     True
Name: physics, dtype: bool

In [7]:
df[f1][f2]

<ipython-input-7-e11c70f9b00c>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[f1][f2]

   roll      name  maths  physics  chemistry  biology
4     5     Abhay     98       95         56       75
9    10  Arshnoor     94       91         40       41

In [8]:
df[f1&f2]

   roll      name  maths  physics  chemistry  biology
4     5     Abhay     98       95         56       75
9    10  Arshnoor     94       91         40       41

In [9]:
df[f1|f2]

   roll      name  maths  physics  chemistry  biology
3     4    Anisha     90       98         89       58
4     5     Abhay     98       95         56       75
9    10  Arshnoor     94       91         40       41

In [11]:
df[f2]

   roll      name  maths  physics  chemistry  biology
3     4    Anisha     90       98         89       58
4     5     Abhay     98       95         56       75
9    10  Arshnoor     94       91         40       41

In [12]:
df[~f2]

   roll    name  maths  physics  chemistry  biology
0     1    Ajay     78       56         90       58
1     2    Amit     87       87         99       97
2     3    Arun     65       76         86       76
5     6     Ram     87       56         67       86
6     7    Sham     89       45         73       35
7     8  Prince     56       78         88       77
8     9   Jatin     90       90         38       97

In [13]:
# WAP to print the roll no of students who have scored marks greater than 85 in either of these subjects
# maths, chemistry, biology

In [17]:
f1 = df['maths'] > 90
f2 = df['chemistry'] > 90
f3 = df['biology'] > 90

In [18]:
df[f1|f2|f3]

   roll      name  maths  physics  chemistry  biology
1     2      Amit     87       87         99       97
4     5     Abhay     98       95         56       75
8     9     Jatin     90       90         38       97
9    10  Arshnoor     94       91         40       41

In [19]:
df['roll'][f1|f2|f3]

1     2
4     5
8     9
9    10
Name: roll, dtype: int64

In [25]:
df['roll'][df['maths']>90]

4     5
9    10
Name: roll, dtype: int64

In [26]:
# WAP to print percentage of following students Amit Abay Jatin

In [30]:
f4 = df['name'] == 'Amit'
f5 = df['name'] == 'Abhay' 
f6 = df['name'] == 'Jatin'

In [31]:
df[f4|f5|f6]

   roll   name  maths  physics  chemistry  biology
1     2   Amit     87       87         99       97
4     5  Abhay     98       95         56       75
8     9  Jatin     90       90         38       97

In [32]:
df['total'] = df['maths'] + df['chemistry'] + df['physics'] + df['biology']

In [33]:
df['percentage'] = df['total'] * 100 / 400

In [34]:
df

   roll      name  maths  physics  chemistry  biology  total  percentage
0     1      Ajay     78       56         90       58    282       70.50
1     2      Amit     87       87         99       97    370       92.50
2     3      Arun     65       76         86       76    303       75.75
3     4    Anisha     90       98         89       58    335       83.75
4     5     Abhay     98       95         56       75    324       81.00
5     6       Ram     87       56         67       86    296       74.00
6     7      Sham     89       45         73       35    242       60.50
7     8    Prince     56       78         88       77    299       74.75
8     9     Jatin     90       90         38       97    315       78.75
9    10  Arshnoor     94       91         40       41    266       66.50

In [35]:
df[['name', 'roll', 'percentage']]

       name  roll  percentage
0      Ajay     1       70.50
1      Amit     2       92.50
2      Arun     3       75.75
3    Anisha     4       83.75
4     Abhay     5       81.00
5       Ram     6       74.00
6      Sham     7       60.50
7    Prince     8       74.75
8     Jatin     9       78.75
9  Arshnoor    10       66.50

In [36]:
df[['name', 'roll', 'percentage']][f4|f5|f6]

    name  roll  percentage
1   Amit     2       92.50
4  Abhay     5       81.00
8  Jatin     9       78.75

In [42]:
f7 = df['name'].isin(['Amit', 'Abhay', 'Arshnoor'])
f7

0    False
1     True
2    False
3    False
4     True
5    False
6    False
7    False
8    False
9     True
Name: name, dtype: bool

In [44]:
df[['name', 'roll','percentage']][f7]

       name  roll  percentage
1      Amit     2        92.5
4     Abhay     5        81.0
9  Arshnoor    10        66.5

In [45]:
df[['name', 'roll','percentage']][df['name'].isin(['Abhay', 'Amit'])]

    name  roll  percentage
1   Amit     2        92.5
4  Abhay     5        81.0

In [46]:
df[['name', 'total','percentage']][df['roll'].isin([1,2,3,4,5,6,7])]

     name  total  percentage
0    Ajay    282       70.50
1    Amit    370       92.50
2    Arun    303       75.75
3  Anisha    335       83.75
4   Abhay    324       81.00
5     Ram    296       74.00
6    Sham    242       60.50

In [49]:
df.nsmallest(4, 'maths')

   roll    name  maths  physics  chemistry  biology  total  percentage
7     8  Prince     56       78         88       77    299       74.75
2     3    Arun     65       76         86       76    303       75.75
0     1    Ajay     78       56         90       58    282       70.50
1     2    Amit     87       87         99       97    370       92.50

In [50]:
df.nsmallest(3, 'total')

   roll      name  maths  physics  chemistry  biology  total  percentage
6     7      Sham     89       45         73       35    242        60.5
9    10  Arshnoor     94       91         40       41    266        66.5
0     1      Ajay     78       56         90       58    282        70.5

In [51]:
df[['roll', 'name', 'total']].nsmallest(3, 'total')

   roll      name  total
6     7      Sham    242
9    10  Arshnoor    266
0     1      Ajay    282

In [52]:
df.nlargest(3, 'total')

   roll    name  maths  physics  chemistry  biology  total  percentage
1     2    Amit     87       87         99       97    370       92.50
3     4  Anisha     90       98         89       58    335       83.75
4     5   Abhay     98       95         56       75    324       81.00

In [53]:
df[['roll', 'name', 'total']].nlargest(3, 'total')

   roll    name  total
1     2    Amit    370
3     4  Anisha    335
4     5   Abhay    324