In [1]:
import pandas as pd

In [2]:
d = {
    'roll':[1,2,3,4,5,6,7,8,9,10],
    'name':['Ajay', 'Amit', 'Arun', 'Anisha', 'Abhay','Ram', 'Sham',
           'Prince', 'Jatin', 'Arshnoor'],
    'maths':[78,87,65,90,98,87,89,56,90,94],
    'physics':[56,87,76,98,95,56,45,78,90,91],
    'chemistry':[90,99,86,89,56,67,73,88,38,40],
    'biology':[58,97,76,58,75,86,35,77,97,41],
}
df = pd.DataFrame(d)
df

   roll      name  maths  physics  chemistry  biology
0     1      Ajay     78       56         90       58
1     2      Amit     87       87         99       97
2     3      Arun     65       76         86       76
3     4    Anisha     90       98         89       58
4     5     Abhay     98       95         56       75
5     6       Ram     87       56         67       86
6     7      Sham     89       45         73       35
7     8    Prince     56       78         88       77
8     9     Jatin     90       90         38       97
9    10  Arshnoor     94       91         40       41

In [3]:
df['name']

0        Ajay
1        Amit
2        Arun
3      Anisha
4       Abhay
5         Ram
6        Sham
7      Prince
8       Jatin
9    Arshnoor
Name: name, dtype: object

In [4]:
df.name

0        Ajay
1        Amit
2        Arun
3      Anisha
4       Abhay
5         Ram
6        Sham
7      Prince
8       Jatin
9    Arshnoor
Name: name, dtype: object

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   roll       10 non-null     int64
 1   name       10 non-null     object
 2   maths      10 non-null     int64
 3   physics    10 non-null     int64
 4   chemistry  10 non-null     int64
 5   biology    10 non-null     int64
dtypes: int64(5), object(1)
memory usage: 608.0+ bytes

In [6]:
df.describe()

           roll      maths    physics  chemistry    biology
count  10.00000  10.000000  10.000000   10.00000  10.000000
mean    5.50000  83.400000  77.200000   72.60000  70.000000
std     3.02765  13.284912  18.671428   21.73681  21.545817
min     1.00000  56.000000  45.000000   38.00000  35.000000
25%     3.25000  80.250000  61.000000   58.75000  58.000000
50%     5.50000  88.000000  82.500000   79.50000  75.500000
75%     7.75000  90.000000  90.750000   88.75000  83.750000
max    10.00000  98.000000  98.000000   99.00000  97.000000

In [8]:
df.maths

0    78
1    87
2    65
3    90
4    98
5    87
6    89
7    56
8    90
9    94
Name: maths, dtype: int64

In [9]:
print(min(df.maths))

56

In [10]:
print(max(df['maths']))

98

In [11]:
print(sum(df['maths']))

834

In [13]:
df['roll']

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: roll, dtype: int64

### Filtering Data from DataFrame

In [14]:
# WAP to filter data of those students with marks greater than 90 in maths

In [16]:
# Step 1 - Create a Filter list/series/array which contains only boolean values

filter1 = df['maths']>90
filter1

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7    False
8    False
9     True
Name: maths, dtype: bool

In [20]:
# Step 2 - Apply filter list to the DataFrame

df[filter1]

   roll      name  maths  physics  chemistry  biology
4     5     Abhay     98       95         56       75
9    10  Arshnoor     94       91         40       41

In [25]:
df[['name', 'roll', 'maths']]

       name  roll  maths
0      Ajay     1     78
1      Amit     2     87
2      Arun     3     65
3    Anisha     4     90
4     Abhay     5     98
5       Ram     6     87
6      Sham     7     89
7    Prince     8     56
8     Jatin     9     90
9  Arshnoor    10     94

In [26]:
df[['name', 'roll', 'maths']][filter1]

       name  roll  maths
4     Abhay     5     98
9  Arshnoor    10     94

In [27]:
# WAP to filter students who have marks greater than 80 in physics and greater that 75 in chemistry

In [34]:
filter2 = df['physics'] > 80
filter3 = df['chemistry'] > 75

In [37]:
df[filter2][filter3]

<ipython-input-37-081a91b0de35>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[filter2][filter3]

   roll    name  maths  physics  chemistry  biology
1     2    Amit     87       87         99       97
3     4  Anisha     90       98         89       58

In [38]:
df[df['biology']>60]

   roll    name  maths  physics  chemistry  biology
1     2    Amit     87       87         99       97
2     3    Arun     65       76         86       76
4     5   Abhay     98       95         56       75
5     6     Ram     87       56         67       86
7     8  Prince     56       78         88       77
8     9   Jatin     90       90         38       97

In [39]:
df[df.name == 'Amit']

   roll  name  maths  physics  chemistry  biology
1     2  Amit     87       87         99       97

### query function

In [42]:
df.query("maths > 70")

   roll      name  maths  physics  chemistry  biology
0     1      Ajay     78       56         90       58
1     2      Amit     87       87         99       97
3     4    Anisha     90       98         89       58
4     5     Abhay     98       95         56       75
5     6       Ram     87       56         67       86
6     7      Sham     89       45         73       35
8     9     Jatin     90       90         38       97
9    10  Arshnoor     94       91         40       41

In [43]:
df.query("chemistry > 70 and physics > 90")

   roll    name  maths  physics  chemistry  biology
3     4  Anisha     90       98         89       58

In [44]:
df['total'] = df['maths'] + df['physics']+df['chemistry']+df['biology']

In [45]:
df

   roll      name  maths  physics  chemistry  biology  total
0     1      Ajay     78       56         90       58    282
1     2      Amit     87       87         99       97    370
2     3      Arun     65       76         86       76    303
3     4    Anisha     90       98         89       58    335
4     5     Abhay     98       95         56       75    324
5     6       Ram     87       56         67       86    296
6     7      Sham     89       45         73       35    242
7     8    Prince     56       78         88       77    299
8     9     Jatin     90       90         38       97    315
9    10  Arshnoor     94       91         40       41    266

In [46]:
df['percentage(%)'] = (df['total'] * 100 ) / 400

In [47]:
df

   roll      name  maths  physics  chemistry  biology  total  percentage(%)
0     1      Ajay     78       56         90       58    282          70.50
1     2      Amit     87       87         99       97    370          92.50
2     3      Arun     65       76         86       76    303          75.75
3     4    Anisha     90       98         89       58    335          83.75
4     5     Abhay     98       95         56       75    324          81.00
5     6       Ram     87       56         67       86    296          74.00
6     7      Sham     89       45         73       35    242          60.50
7     8    Prince     56       78         88       77    299          74.75
8     9     Jatin     90       90         38       97    315          78.75
9    10  Arshnoor     94       91         40       41    266          66.50

In [48]:
df[df['percentage(%)'] > 80]

   roll    name  maths  physics  chemistry  biology  total  percentage(%)
1     2    Amit     87       87         99       97    370          92.50
3     4  Anisha     90       98         89       58    335          83.75
4     5   Abhay     98       95         56       75    324          81.00

In [49]:
df.query("name == 'Abhay'")

   roll   name  maths  physics  chemistry  biology  total  percentage(%)
4     5  Abhay     98       95         56       75    324           81.0

In [55]:
df.query("chemistry > 81")

   roll    name  maths  physics  chemistry  biology  total  percentage(%)
0     1    Ajay     78       56         90       58    282          70.50
1     2    Amit     87       87         99       97    370          92.50
2     3    Arun     65       76         86       76    303          75.75
3     4  Anisha     90       98         89       58    335          83.75
7     8  Prince     56       78         88       77    299          74.75

In [56]:
df.head(3)

   roll  name  maths  physics  chemistry  biology  total  percentage(%)
0     1  Ajay     78       56         90       58    282          70.50
1     2  Amit     87       87         99       97    370          92.50
2     3  Arun     65       76         86       76    303          75.75

In [57]:
df.tail(2)

   roll      name  maths  physics  chemistry  biology  total  percentage(%)
8     9     Jatin     90       90         38       97    315          78.75
9    10  Arshnoor     94       91         40       41    266          66.50

In [58]:
df.query("chemistry > 79 and biology > 80")

   roll  name  maths  physics  chemistry  biology  total  percentage(%)
1     2  Amit     87       87         99       97    370           92.5

In [59]:
df.query('maths > 90 or chemistry > 90 or biology > 90 or physics > 90')

   roll      name  maths  physics  chemistry  biology  total  percentage(%)
1     2      Amit     87       87         99       97    370          92.50
3     4    Anisha     90       98         89       58    335          83.75
4     5     Abhay     98       95         56       75    324          81.00
8     9     Jatin     90       90         38       97    315          78.75
9    10  Arshnoor     94       91         40       41    266          66.50

In [60]:
df = pd.read_csv('Pokemon.csv')
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [ ]:
# WAP to filter pokemons with highest hitpoints of four categories water, fire, electric,grass in all generations