In [1]:
import pandas as pd

In [2]:
d = {
    'roll':[1,2,3,4,5,6,7,8,9,10],
    'name':['Ajay', 'Amit', 'Arun', 'Anisha', 'Abhay','Ram', 'Sham',
           'Prince', 'Jatin', 'Arshnoor'],
    'maths':[78,87,65,90,98,87,89,56,90,94],
    'physics':[56,87,76,98,95,56,45,78,90,91],
    'chemistry':[90,99,86,89,56,67,73,88,38,40],
    'biology':[58,97,76,58,75,86,35,77,97,41],
}
df = pd.DataFrame(d)
df

   roll      name  maths  physics  chemistry  biology
0     1      Ajay     78       56         90       58
1     2      Amit     87       87         99       97
2     3      Arun     65       76         86       76
3     4    Anisha     90       98         89       58
4     5     Abhay     98       95         56       75
5     6       Ram     87       56         67       86
6     7      Sham     89       45         73       35
7     8    Prince     56       78         88       77
8     9     Jatin     90       90         38       97
9    10  Arshnoor     94       91         40       41

### loc and iloc functions

In [3]:
df.loc[3:9]

   roll      name  maths  physics  chemistry  biology
3     4    Anisha     90       98         89       58
4     5     Abhay     98       95         56       75
5     6       Ram     87       56         67       86
6     7      Sham     89       45         73       35
7     8    Prince     56       78         88       77
8     9     Jatin     90       90         38       97
9    10  Arshnoor     94       91         40       41

In [4]:
df.iloc[3:9]

   roll    name  maths  physics  chemistry  biology
3     4  Anisha     90       98         89       58
4     5   Abhay     98       95         56       75
5     6     Ram     87       56         67       86
6     7    Sham     89       45         73       35
7     8  Prince     56       78         88       77
8     9   Jatin     90       90         38       97

#### loc function

In [6]:
# DataFrame.loc[row_index, column_name]
# DataFrame.loc[row_index]

In [7]:
df.loc[1]

roll            2
name         Amit
maths          87
physics        87
chemistry      99
biology        97
Name: 1, dtype: object

In [9]:
df.loc[1:4]

   roll    name  maths  physics  chemistry  biology
1     2    Amit     87       87         99       97
2     3    Arun     65       76         86       76
3     4  Anisha     90       98         89       58
4     5   Abhay     98       95         56       75

In [10]:
df.loc[[1,3,5,7]]

   roll    name  maths  physics  chemistry  biology
1     2    Amit     87       87         99       97
3     4  Anisha     90       98         89       58
5     6     Ram     87       56         67       86
7     8  Prince     56       78         88       77

In [13]:
df.loc[1:4, 'name']

1      Amit
2      Arun
3    Anisha
4     Abhay
Name: name, dtype: object

In [14]:
df.loc[1:6,['roll', 'name']]

   roll    name
1     2    Amit
2     3    Arun
3     4  Anisha
4     5   Abhay
5     6     Ram
6     7    Sham

In [17]:
df.loc[[1,3,5,7], ['roll', 'maths', 'physics']]

   roll  maths  physics
1     2     87       87
3     4     90       98
5     6     87       56
7     8     56       78

#### iloc function

In [20]:
# DataFrame.iloc['row_index', 'column_index']
# DataFrame.iloc['row_index']

In [21]:
df

   roll      name  maths  physics  chemistry  biology
0     1      Ajay     78       56         90       58
1     2      Amit     87       87         99       97
2     3      Arun     65       76         86       76
3     4    Anisha     90       98         89       58
4     5     Abhay     98       95         56       75
5     6       Ram     87       56         67       86
6     7      Sham     89       45         73       35
7     8    Prince     56       78         88       77
8     9     Jatin     90       90         38       97
9    10  Arshnoor     94       91         40       41

In [22]:
df.iloc[2:7]

   roll    name  maths  physics  chemistry  biology
2     3    Arun     65       76         86       76
3     4  Anisha     90       98         89       58
4     5   Abhay     98       95         56       75
5     6     Ram     87       56         67       86
6     7    Sham     89       45         73       35

In [23]:
df.iloc[2]

roll            3
name         Arun
maths          65
physics        76
chemistry      86
biology        76
Name: 2, dtype: object

In [24]:
df.iloc[[1,2,3,5,7]]

   roll    name  maths  physics  chemistry  biology
1     2    Amit     87       87         99       97
2     3    Arun     65       76         86       76
3     4  Anisha     90       98         89       58
5     6     Ram     87       56         67       86
7     8  Prince     56       78         88       77

In [25]:
df.iloc[2:5, 1]

2      Arun
3    Anisha
4     Abhay
Name: name, dtype: object

In [26]:
df.iloc[2:6, [0,1,4]]

   roll    name  chemistry
2     3    Arun         86
3     4  Anisha         89
4     5   Abhay         56
5     6     Ram         67

In [27]:
df.iloc[2:6, 0:4]

   roll    name  maths  physics
2     3    Arun     65       76
3     4  Anisha     90       98
4     5   Abhay     98       95
5     6     Ram     87       56

In [28]:
df.iloc[[1,3,5,7,9] , [0,2,4]]

   roll  maths  chemistry
1     2     87         99
3     4     90         89
5     6     87         67
7     8     56         88
9    10     94         40

In [29]:
df

   roll      name  maths  physics  chemistry  biology
0     1      Ajay     78       56         90       58
1     2      Amit     87       87         99       97
2     3      Arun     65       76         86       76
3     4    Anisha     90       98         89       58
4     5     Abhay     98       95         56       75
5     6       Ram     87       56         67       86
6     7      Sham     89       45         73       35
7     8    Prince     56       78         88       77
8     9     Jatin     90       90         38       97
9    10  Arshnoor     94       91         40       41

### Updating the dataframe Data

In [30]:
df.iloc[0,1]

'Ajay'

In [31]:
df.iloc[0,1] = "Ajay Kumar"

In [32]:
df

   roll        name  maths  physics  chemistry  biology
0     1  Ajay Kumar     78       56         90       58
1     2        Amit     87       87         99       97
2     3        Arun     65       76         86       76
3     4      Anisha     90       98         89       58
4     5       Abhay     98       95         56       75
5     6         Ram     87       56         67       86
6     7        Sham     89       45         73       35
7     8      Prince     56       78         88       77
8     9       Jatin     90       90         38       97
9    10    Arshnoor     94       91         40       41

In [33]:
df.loc[9, 'chemistry']

40

In [34]:
df.loc[9, 'chemistry'] = 90

In [35]:
df.loc[9, 'biology'] = 87

In [36]:
df

   roll        name  maths  physics  chemistry  biology
0     1  Ajay Kumar     78       56         90       58
1     2        Amit     87       87         99       97
2     3        Arun     65       76         86       76
3     4      Anisha     90       98         89       58
4     5       Abhay     98       95         56       75
5     6         Ram     87       56         67       86
6     7        Sham     89       45         73       35
7     8      Prince     56       78         88       77
8     9       Jatin     90       90         38       97
9    10    Arshnoor     94       91         90       87

### Adding a New Column

In [37]:
fathername = ['a','b','c','d','e','f','g','h','i','j']

In [38]:
df['fathername'] = fathername

In [39]:
df

   roll        name  maths  physics  chemistry  biology fathername
0     1  Ajay Kumar     78       56         90       58          a
1     2        Amit     87       87         99       97          b
2     3        Arun     65       76         86       76          c
3     4      Anisha     90       98         89       58          d
4     5       Abhay     98       95         56       75          e
5     6         Ram     87       56         67       86          f
6     7        Sham     89       45         73       35          g
7     8      Prince     56       78         88       77          h
8     9       Jatin     90       90         38       97          i
9    10    Arshnoor     94       91         90       87          j

#### insert funtion

In [43]:
df.insert(2,'fathername', fathername)

In [44]:
df

   roll        name fathername  maths  physics  chemistry  biology
0     1  Ajay Kumar          a     78       56         90       58
1     2        Amit          b     87       87         99       97
2     3        Arun          c     65       76         86       76
3     4      Anisha          d     90       98         89       58
4     5       Abhay          e     98       95         56       75
5     6         Ram          f     87       56         67       86
6     7        Sham          g     89       45         73       35
7     8      Prince          h     56       78         88       77
8     9       Jatin          i     90       90         38       97
9    10    Arshnoor          j     94       91         90       87

### Removing a Column from dataframe

##### pop function

In [40]:
df.pop('fathername')

0    a
1    b
2    c
3    d
4    e
5    f
6    g
7    h
8    i
9    j
Name: fathername, dtype: object

In [41]:
df

   roll        name  maths  physics  chemistry  biology
0     1  Ajay Kumar     78       56         90       58
1     2        Amit     87       87         99       97
2     3        Arun     65       76         86       76
3     4      Anisha     90       98         89       58
4     5       Abhay     98       95         56       75
5     6         Ram     87       56         67       86
6     7        Sham     89       45         73       35
7     8      Prince     56       78         88       77
8     9       Jatin     90       90         38       97
9    10    Arshnoor     94       91         90       87

##### other functions

In [48]:
df.index[5]

5

### drop function

In [52]:
df.drop(3)  # Deleting a row from DataFrame

   roll        name fathername  maths  physics  chemistry  biology
0     1  Ajay Kumar          a     78       56         90       58
1     2        Amit          b     87       87         99       97
2     3        Arun          c     65       76         86       76
4     5       Abhay          e     98       95         56       75
5     6         Ram          f     87       56         67       86
6     7        Sham          g     89       45         73       35
7     8      Prince          h     56       78         88       77
8     9       Jatin          i     90       90         38       97
9    10    Arshnoor          j     94       91         90       87

In [53]:
df.drop(df.index[3])

   roll        name fathername  maths  physics  chemistry  biology
0     1  Ajay Kumar          a     78       56         90       58
1     2        Amit          b     87       87         99       97
2     3        Arun          c     65       76         86       76
4     5       Abhay          e     98       95         56       75
5     6         Ram          f     87       56         67       86
6     7        Sham          g     89       45         73       35
7     8      Prince          h     56       78         88       77
8     9       Jatin          i     90       90         38       97
9    10    Arshnoor          j     94       91         90       87

In [51]:
df.drop('fathername', axis=1) # deleting a column from DataFrame

   roll        name  maths  physics  chemistry  biology
0     1  Ajay Kumar     78       56         90       58
1     2        Amit     87       87         99       97
2     3        Arun     65       76         86       76
3     4      Anisha     90       98         89       58
4     5       Abhay     98       95         56       75
5     6         Ram     87       56         67       86
6     7        Sham     89       45         73       35
7     8      Prince     56       78         88       77
8     9       Jatin     90       90         38       97
9    10    Arshnoor     94       91         90       87

### String Filters

In [55]:
df[df['name'].str.contains('am')]

   roll  name fathername  maths  physics  chemistry  biology
5     6   Ram          f     87       56         67       86
6     7  Sham          g     89       45         73       35

In [56]:
df[df['name'].str.contains('A')]

   roll        name fathername  maths  physics  chemistry  biology
0     1  Ajay Kumar          a     78       56         90       58
1     2        Amit          b     87       87         99       97
2     3        Arun          c     65       76         86       76
3     4      Anisha          d     90       98         89       58
4     5       Abhay          e     98       95         56       75
9    10    Arshnoor          j     94       91         90       87

In [57]:
df[df['name'].str.contains('a')]

   roll        name fathername  maths  physics  chemistry  biology
0     1  Ajay Kumar          a     78       56         90       58
3     4      Anisha          d     90       98         89       58
4     5       Abhay          e     98       95         56       75
5     6         Ram          f     87       56         67       86
6     7        Sham          g     89       45         73       35
8     9       Jatin          i     90       90         38       97

In [60]:
df[df['name'].str.startswith('S')]

   roll  name fathername  maths  physics  chemistry  biology
6     7  Sham          g     89       45         73       35

In [61]:
df[df['name'].str.endswith('r')]

   roll        name fathername  maths  physics  chemistry  biology
0     1  Ajay Kumar          a     78       56         90       58
9    10    Arshnoor          j     94       91         90       87