In [1]:
import pandas
import numpy

In [2]:
arr2d = numpy.array([[1,2,3,4],[5,6,7,8]])
arr2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
arr2d.shape

(2, 4)

In [4]:
df = pandas.DataFrame([1,2,3,4,5])
print(df)

   0
0  1
1  2
2  3
3  4
4  5

In [5]:
df1 = pandas.DataFrame([[1,2,3,4,5],[6,7,8,9,0]])
print(df1)

   0  1  2  3  4
0  1  2  3  4  5
1  6  7  8  9  0

In [7]:
df3 = pandas.DataFrame([[1,2,3,4,5],[6,7,8,9,0]], index=['a','b'], columns=['a','b','c','d','e'])
print(df3)

   a  b  c  d  e
a  1  2  3  4  5
b  6  7  8  9  0

In [8]:
df3

   a  b  c  d  e
a  1  2  3  4  5
b  6  7  8  9  0

### Creating DataFrame using Dictionary

In [9]:
d = {
    'rollno':[1,2,3,4,5],
    'name':['Aman', 'Ajay', 'Arshnoor', 'Jatin', 'Vasu'],
    'class':['BCA', 'BCA', 'Btech', 'MCA', 'BCA']
}
df4 = pandas.DataFrame(d)
df4

   rollno      name  class
0       1      Aman    BCA
1       2      Ajay    BCA
2       3  Arshnoor  Btech
3       4     Jatin    MCA
4       5      Vasu    BCA

In [10]:
print(df4)

   rollno      name  class
0       1      Aman    BCA
1       2      Ajay    BCA
2       3  Arshnoor  Btech
3       4     Jatin    MCA
4       5      Vasu    BCA

In [11]:
df = pandas.read_csv("students.csv")
df

    roll     name class  marks
0      1    rahul   bca     56
1      2    vikas   bca     54
2      3     vasu   bca     76
3      4     ajay   bca     89
4      5  avinoor   bca     65
5      6    jatin   bca     90
6      7    vijay   bca     45
7      8     amit   bca     23
8      9   gaurav   bca     78

In [12]:
df1 = pandas.read_excel("students.xlsx")
df1

    roll     name class  marks
0      1    rahul   bca     56
1      2    vikas   bca     54
2      3     vasu   bca     76
3      4     ajay   bca     89
4      5  avinoor   bca     65
5      6    jatin   bca     90
6      7    vijay   bca     45
7      8     amit   bca     23
8      9   gaurav   bca     78

In [13]:
df['name']

0      rahul
1      vikas
2       vasu
3       ajay
4    avinoor
5      jatin
6      vijay
7       amit
8     gaurav
Name: name, dtype: object

In [14]:
df.name

0      rahul
1      vikas
2       vasu
3       ajay
4    avinoor
5      jatin
6      vijay
7       amit
8     gaurav
Name: name, dtype: object

In [15]:
df.to_csv('D://VMM MACHINE LEARNING//Day 7//new_students.csv')

In [16]:
df.to_excel('D://VMM MACHINE LEARNING//Day 7//new_students1.xlsx')

In [17]:
df.to_clipboard()

In [18]:
df.to_clipboard(sep=',')

In [19]:
df.to_dict()

{' roll': {0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9},
 'name': {0: 'rahul',
  1: 'vikas',
  2: 'vasu',
  3: 'ajay',
  4: 'avinoor',
  5: 'jatin',
  6: 'vijay',
  7: 'amit',
  8: 'gaurav'},
 'class': {0: 'bca',
  1: 'bca',
  2: 'bca',
  3: 'bca',
  4: 'bca',
  5: 'bca',
  6: 'bca',
  7: 'bca',
  8: 'bca'},
 'marks': {0: 56, 1: 54, 2: 76, 3: 89, 4: 65, 5: 90, 6: 45, 7: 23, 8: 78}}

In [20]:
df = pandas.read_csv('ds_salaries.csv')
df

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L
...,...,...,...,...,...,...,...,...,...,...,...,...
602,602,2022,SE,FT,Data Engineer,154000,USD,154000,US,100,US,M
603,603,2022,SE,FT,Data Engineer,126000,USD,126000,US,100,US,M
604,604,2022,SE,FT,Data Analyst,129000,USD,129000,US,0,US,M
605,605,2022,SE,FT,Data Analyst,150000,USD,150000,US,100,US,M
606,606,2022,MI,FT,AI Scientist,200000,USD,200000,IN,100,US,L

In [21]:
df.head()

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L

In [22]:
df.head(3)

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M

In [23]:
df.head(9)

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L
5,5,2020,EN,FT,Data Analyst,72000,USD,72000,US,100,US,L
6,6,2020,SE,FT,Lead Data Scientist,190000,USD,190000,US,100,US,S
7,7,2020,MI,FT,Data Scientist,11000000,HUF,35735,HU,50,HU,L
8,8,2020,MI,FT,Business Data Analyst,135000,USD,135000,US,100,US,L

In [24]:
df.tail()

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
602,602,2022,SE,FT,Data Engineer,154000,USD,154000,US,100,US,M
603,603,2022,SE,FT,Data Engineer,126000,USD,126000,US,100,US,M
604,604,2022,SE,FT,Data Analyst,129000,USD,129000,US,0,US,M
605,605,2022,SE,FT,Data Analyst,150000,USD,150000,US,100,US,M
606,606,2022,MI,FT,AI Scientist,200000,USD,200000,IN,100,US,L

In [25]:
df.tail(8)

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
599,599,2022,MI,FT,Data Scientist,130000,USD,130000,US,100,US,M
600,600,2022,EN,FT,Data Analyst,67000,USD,67000,CA,0,CA,M
601,601,2022,EN,FT,Data Analyst,52000,USD,52000,CA,0,CA,M
602,602,2022,SE,FT,Data Engineer,154000,USD,154000,US,100,US,M
603,603,2022,SE,FT,Data Engineer,126000,USD,126000,US,100,US,M
604,604,2022,SE,FT,Data Analyst,129000,USD,129000,US,0,US,M
605,605,2022,SE,FT,Data Analyst,150000,USD,150000,US,100,US,M
606,606,2022,MI,FT,AI Scientist,200000,USD,200000,IN,100,US,L

In [30]:
salary = ['salary']
max_value =salary.max()

AttributeError: 'list' object has no attribute 'max'