In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('EmployeeData.csv')
df

    EMPID            Ename  Salary Department  Gender  Age
0    1001   Arshnoor Singh  100000         DS    Male   21
1    1002       Tony Stark  100000        CSE    Male   50
2    1003             Thor   70000         ME    Male   70
3    1004    Scarlet Witch    5000         CE  Female   30
4    1005   Doctor Strange   50000       MBBS    Male   45
5    1006        Spiderman   30000        CSE    Male   25
6    1007         Stan Lee   90000       ARTS    Male   90
7    1008   Sheldon Cooper   45000         TP    Male   27
8    1009  Howard Wolowitz   50000         ME    Male   28
9    1010    Leonard Nimoy   20000       ARTS    Male   67
10   1011     Bruce Banner   50000        CSE    Male   45
11   1012      Bruce Wayne   99000        CSE    Male   35
12   1013  Caption America   60000         ME    Male   70
13   1014      Black Widow   25000         ME  Female   29
14   1015           Vision   30000        ECE    Male   30
15   1017   David Eagleman   40000        ECE    Male   35
16   1018         Jim Kwik   37000        CSE    Male   40
17   1019        Elon Musk   91000        CSE    Male   50
18   1020    Robert Greene   49000         ME    Male   67
19   1021    Napoleon Hill   90000         ME    Male   78
20   1022    Ankur Warikoo   25000        CSE  Female   40
21   1023      Cal Newport   35000        CSE    Male   34
22   1024       Jay Shetty   35000        ECE  Female   33
23   1025  Sherlock Holmes   80000        CSE    Male   32
24   1026  Stephen Hawking   95000         TP    Male   89
25   1027     Chris Bailey   31000        ECE    Male   56
26   1028          Meg Jay   20000         ME  Female   54
27   1029      Brian Tracy   30000         CE  Female   78
28   1030      Joshua Foer   43000        CSE  Female   36

In [3]:
# 1. Find Details of all Male Members in the CSE Dept
df[df['Gender'] == 'Male']

    EMPID            Ename  Salary Department Gender  Age
0    1001   Arshnoor Singh  100000         DS   Male   21
1    1002       Tony Stark  100000        CSE   Male   50
2    1003             Thor   70000         ME   Male   70
4    1005   Doctor Strange   50000       MBBS   Male   45
5    1006        Spiderman   30000        CSE   Male   25
6    1007         Stan Lee   90000       ARTS   Male   90
7    1008   Sheldon Cooper   45000         TP   Male   27
8    1009  Howard Wolowitz   50000         ME   Male   28
9    1010    Leonard Nimoy   20000       ARTS   Male   67
10   1011     Bruce Banner   50000        CSE   Male   45
11   1012      Bruce Wayne   99000        CSE   Male   35
12   1013  Caption America   60000         ME   Male   70
14   1015           Vision   30000        ECE   Male   30
15   1017   David Eagleman   40000        ECE   Male   35
16   1018         Jim Kwik   37000        CSE   Male   40
17   1019        Elon Musk   91000        CSE   Male   50
18   1020    Robert Greene   49000         ME   Male   67
19   1021    Napoleon Hill   90000         ME   Male   78
21   1023      Cal Newport   35000        CSE   Male   34
23   1025  Sherlock Holmes   80000        CSE   Male   32
24   1026  Stephen Hawking   95000         TP   Male   89
25   1027     Chris Bailey   31000        ECE   Male   56

In [4]:
# 2. Find 3 Highest paid employees in CSE Department 
df2 = df[['EMPID','Ename','Salary']][df['Department'].isin(['CSE'])]
df2.nlargest(3,'Salary')

    EMPID        Ename  Salary
1    1002   Tony Stark  100000
11   1012  Bruce Wayne   99000
17   1019    Elon Musk   91000

In [5]:
# 3. Find 3 Lowest Paid employees in the whole company
df.nsmallest(3,'Salary')

    EMPID          Ename  Salary Department  Gender  Age
3    1004  Scarlet Witch    5000         CE  Female   30
9    1010  Leonard Nimoy   20000       ARTS    Male   67
26   1028        Meg Jay   20000         ME  Female   54

In [6]:
# 4. Add a new column of dearness allowance which will be equivalent to 17 percent of the total salary
df['Dearness Allowance'] = df['Salary']/100 * 17
df

    EMPID            Ename  Salary Department  Gender  Age  Dearness Allowance
0    1001   Arshnoor Singh  100000         DS    Male   21             17000.0
1    1002       Tony Stark  100000        CSE    Male   50             17000.0
2    1003             Thor   70000         ME    Male   70             11900.0
3    1004    Scarlet Witch    5000         CE  Female   30               850.0
4    1005   Doctor Strange   50000       MBBS    Male   45              8500.0
5    1006        Spiderman   30000        CSE    Male   25              5100.0
6    1007         Stan Lee   90000       ARTS    Male   90             15300.0
7    1008   Sheldon Cooper   45000         TP    Male   27              7650.0
8    1009  Howard Wolowitz   50000         ME    Male   28              8500.0
9    1010    Leonard Nimoy   20000       ARTS    Male   67              3400.0
10   1011     Bruce Banner   50000        CSE    Male   45              8500.0
11   1012      Bruce Wayne   99000        CSE    Male   35             16830.0
12   1013  Caption America   60000         ME    Male   70             10200.0
13   1014      Black Widow   25000         ME  Female   29              4250.0
14   1015           Vision   30000        ECE    Male   30              5100.0
15   1017   David Eagleman   40000        ECE    Male   35              6800.0
16   1018         Jim Kwik   37000        CSE    Male   40              6290.0
17   1019        Elon Musk   91000        CSE    Male   50             15470.0
18   1020    Robert Greene   49000         ME    Male   67              8330.0
19   1021    Napoleon Hill   90000         ME    Male   78             15300.0
20   1022    Ankur Warikoo   25000        CSE  Female   40              4250.0
21   1023      Cal Newport   35000        CSE    Male   34              5950.0
22   1024       Jay Shetty   35000        ECE  Female   33              5950.0
23   1025  Sherlock Holmes   80000        CSE    Male   32             13600.0
24   1026  Stephen Hawking   95000         TP    Male   89             16150.0
25   1027     Chris Bailey   31000        ECE    Male   56              5270.0
26   1028          Meg Jay   20000         ME  Female   54              3400.0
27   1029      Brian Tracy   30000         CE  Female   78              5100.0
28   1030      Joshua Foer   43000        CSE  Female   36              7310.0

In [7]:
# 5. Add a new column for net salary paid which will have a total of salary + dearness allowance
df['Net Salary'] = df['Salary'] + df['Dearness Allowance']
df

,EMPID,Ename,Salary,Department,Gender,Age,Dearness Allowance,Net Salary
0,1001,Arshnoor Singh,100000,DS,Male,21,17000.0,117000.0
1,1002,Tony Stark,100000,CSE,Male,50,17000.0,117000.0
2,1003,Thor,70000,ME,Male,70,11900.0,81900.0
3,1004,Scarlet Witch,5000,CE,Female,30,850.0,5850.0
4,1005,Doctor Strange,50000,MBBS,Male,45,8500.0,58500.0
5,1006,Spiderman,30000,CSE,Male,25,5100.0,35100.0
6,1007,Stan Lee,90000,ARTS,Male,90,15300.0,105300.0
7,1008,Sheldon Cooper,45000,TP,Male,27,7650.0,52650.0
8,1009,Howard Wolowitz,50000,ME,Male,28,8500.0,58500.0
9,1010,Leonard Nimoy,20000,ARTS,Male,67,3400.0,23400.0
10,1011,Bruce Banner,50000,CSE,Male,45,8500.0,58500.0
11,1012,Bruce Wayne,99000,CSE,Male,35,16830.0,115830.0
12,1013,Caption America,60000,ME,Male,70,10200.0,70200.0
13,1014,Black Widow,25000,ME,Female,29,4250.0,29250.0
14,1015,Vision,30000,ECE,Male,30,5100.0,35100.0
15,1017,David Eagleman,40000,ECE,Male,35,6800.0,46800.0
16,1018,Jim Kwik,37000,CSE,Male,40,6290.0,43290.0
17,1019,Elon Musk,91000,CSE,Male,50,15470.0,106470.0
18,1020,Robert Greene,49000,ME,Male,67,8330.0,57330.0
19,1021,Napoleon Hill,90000,ME,Male,78,15300.0,105300.0
20,1022,Ankur Warikoo,25000,CSE,Female,40,4250.0,29250.0
21,1023,Cal Newport,35000,CSE,Male,34,5950.0,40950.0
22,1024,Jay Shetty,35000,ECE,Female,33,5950.0,40950.0
23,1025,Sherlock Holmes,80000,CSE,Male,32,13600.0,93600.0
24,1026,Stephen Hawking,95000,TP,Male,89,16150.0,111150.0
25,1027,Chris Bailey,31000,ECE,Male,56,5270.0,36270.0
26,1028,Meg Jay,20000,ME,Female,54,3400.0,23400.0
27,1029,Brian Tracy,30000,CE,Female,78,5100.0,35100.0
28,1030,Joshua Foer,43000,CSE,Female,36,7310.0,50310.0

In [8]:
#6.	Find How Total Salary is being paid to all employees output should be 
# Total Salary  	 Total Dearness Allowance   	  Total Amount

In [18]:
# 7. Remove all Employees of department ECE 
df2 = df.loc[(df['Department'] == 'ECE')]
df2.index
df.drop(df2.index)

,EMPID,Ename,Salary,Department,Gender,Age,Dearness Allowance,Net Salary
0,1001,Arshnoor Singh,100000,DS,Male,21,17000.0,117000.0
1,1002,Tony Stark,100000,CSE,Male,50,17000.0,117000.0
2,1003,Thor,70000,ME,Male,70,11900.0,81900.0
3,1004,Scarlet Witch,5000,CE,Female,30,850.0,5850.0
4,1005,Doctor Strange,50000,MBBS,Male,45,8500.0,58500.0
5,1006,Spiderman,30000,CSE,Male,25,5100.0,35100.0
6,1007,Stan Lee,90000,ARTS,Male,90,15300.0,105300.0
7,1008,Sheldon Cooper,45000,TP,Male,27,7650.0,52650.0
8,1009,Howard Wolowitz,50000,ME,Male,28,8500.0,58500.0
9,1010,Leonard Nimoy,20000,ARTS,Male,67,3400.0,23400.0
10,1011,Bruce Banner,50000,CSE,Male,45,8500.0,58500.0
11,1012,Bruce Wayne,99000,CSE,Male,35,16830.0,115830.0
12,1013,Caption America,60000,ME,Male,70,10200.0,70200.0
13,1014,Black Widow,25000,ME,Female,29,4250.0,29250.0
16,1018,Jim Kwik,37000,CSE,Male,40,6290.0,43290.0
17,1019,Elon Musk,91000,CSE,Male,50,15470.0,106470.0
18,1020,Robert Greene,49000,ME,Male,67,8330.0,57330.0
19,1021,Napoleon Hill,90000,ME,Male,78,15300.0,105300.0
20,1022,Ankur Warikoo,25000,CSE,Female,40,4250.0,29250.0
21,1023,Cal Newport,35000,CSE,Male,34,5950.0,40950.0
23,1025,Sherlock Holmes,80000,CSE,Male,32,13600.0,93600.0
24,1026,Stephen Hawking,95000,TP,Male,89,16150.0,111150.0
26,1028,Meg Jay,20000,ME,Female,54,3400.0,23400.0
27,1029,Brian Tracy,30000,CE,Female,78,5100.0,35100.0
28,1030,Joshua Foer,43000,CSE,Female,36,7310.0,50310.0