In [1]:
import pandas as pd

In [2]:
d = {
    'roll':[1,2,3,4,5,6,7,8,9,10],
    'name':['Ajay', 'Amit', 'Arun','Anisha', 'Abhay', 'Ram', 'Sham', 'Prince', 'Jatin', 'Arshnoor'],
    'maths':[78,56,98,5,4,5,7,9,8,100],
    'Physics':[78,5,8,35,74,75,87,89,38,100],
    'chemistry':[78,56,98,95,74,45,77,49,48,100],
    'biology':[78,56,98,57,46,55,47,39,28,100]
}
df = pd.DataFrame(d)
df

   roll      name  maths  Physics  chemistry  biology
0     1      Ajay     78       78         78       78
1     2      Amit     56        5         56       56
2     3      Arun     98        8         98       98
3     4    Anisha      5       35         95       57
4     5     Abhay      4       74         74       46
5     6       Ram      5       75         45       55
6     7      Sham      7       87         77       47
7     8    Prince      9       89         49       39
8     9     Jatin      8       38         48       28
9    10  Arshnoor    100      100        100      100

### loc and iloc functions

In [3]:
df.loc[3:9] #location

   roll      name  maths  Physics  chemistry  biology
3     4    Anisha      5       35         95       57
4     5     Abhay      4       74         74       46
5     6       Ram      5       75         45       55
6     7      Sham      7       87         77       47
7     8    Prince      9       89         49       39
8     9     Jatin      8       38         48       28
9    10  Arshnoor    100      100        100      100

In [4]:
df.iloc[3:9]   #index location

   roll    name  maths  Physics  chemistry  biology
3     4  Anisha      5       35         95       57
4     5   Abhay      4       74         74       46
5     6     Ram      5       75         45       55
6     7    Sham      7       87         77       47
7     8  Prince      9       89         49       39
8     9   Jatin      8       38         48       28

#### loc function

In [5]:
# DataFrame.loc[row_index, column_name]
# DtaFrame.loc[row_index]

In [6]:
df.loc[1]

roll            2
name         Amit
maths          56
Physics         5
chemistry      56
biology        56
Name: 1, dtype: object

In [7]:
df.loc[1:4]

   roll    name  maths  Physics  chemistry  biology
1     2    Amit     56        5         56       56
2     3    Arun     98        8         98       98
3     4  Anisha      5       35         95       57
4     5   Abhay      4       74         74       46

In [9]:
df.loc[[1,3,5,7]]

   roll    name  maths  Physics  chemistry  biology
1     2    Amit     56        5         56       56
3     4  Anisha      5       35         95       57
5     6     Ram      5       75         45       55
7     8  Prince      9       89         49       39

In [10]:
df.loc[1:4, 'name']

1      Amit
2      Arun
3    Anisha
4     Abhay
Name: name, dtype: object

In [11]:
df.loc[1:6, ['roll', 'name']]

   roll    name
1     2    Amit
2     3    Arun
3     4  Anisha
4     5   Abhay
5     6     Ram
6     7    Sham

In [12]:
df.loc[[1,3,5,7], ['roll', 'maths', 'Physics']]

   roll  maths  Physics
1     2     56        5
3     4      5       35
5     6      5       75
7     8      9       89

#### iloc function

In [13]:
# DataFrame.iloc['row_index', 'column_index']
# DataFrame.iloc['row_index']

In [14]:
df

   roll      name  maths  Physics  chemistry  biology
0     1      Ajay     78       78         78       78
1     2      Amit     56        5         56       56
2     3      Arun     98        8         98       98
3     4    Anisha      5       35         95       57
4     5     Abhay      4       74         74       46
5     6       Ram      5       75         45       55
6     7      Sham      7       87         77       47
7     8    Prince      9       89         49       39
8     9     Jatin      8       38         48       28
9    10  Arshnoor    100      100        100      100

In [15]:
df.iloc[2:7]

   roll    name  maths  Physics  chemistry  biology
2     3    Arun     98        8         98       98
3     4  Anisha      5       35         95       57
4     5   Abhay      4       74         74       46
5     6     Ram      5       75         45       55
6     7    Sham      7       87         77       47

In [16]:
df.iloc[2]

roll            3
name         Arun
maths          98
Physics         8
chemistry      98
biology        98
Name: 2, dtype: object

In [17]:
df.iloc[[1,2,3,5,7]]

   roll    name  maths  Physics  chemistry  biology
1     2    Amit     56        5         56       56
2     3    Arun     98        8         98       98
3     4  Anisha      5       35         95       57
5     6     Ram      5       75         45       55
7     8  Prince      9       89         49       39

In [18]:
df.iloc[2:5, 1]

2      Arun
3    Anisha
4     Abhay
Name: name, dtype: object

In [19]:
df.iloc[2:6, [0,1,4]]

   roll    name  chemistry
2     3    Arun         98
3     4  Anisha         95
4     5   Abhay         74
5     6     Ram         45

In [20]:
df.iloc[2:6, 0:4]

   roll    name  maths  Physics
2     3    Arun     98        8
3     4  Anisha      5       35
4     5   Abhay      4       74
5     6     Ram      5       75

In [23]:
df.iloc[[1,3,5,7,9], [0,2,4]]

   roll  maths  chemistry
1     2     56         56
3     4      5         95
5     6      5         45
7     8      9         49
9    10    100        100

### Updating the dataframe data

In [22]:
df.iloc[0,1]

'Ajay'

In [24]:
df.iloc[0,1] = 'Ajay Kumar'

In [25]:
df

   roll        name  maths  Physics  chemistry  biology
0     1  Ajay Kumar     78       78         78       78
1     2        Amit     56        5         56       56
2     3        Arun     98        8         98       98
3     4      Anisha      5       35         95       57
4     5       Abhay      4       74         74       46
5     6         Ram      5       75         45       55
6     7        Sham      7       87         77       47
7     8      Prince      9       89         49       39
8     9       Jatin      8       38         48       28
9    10    Arshnoor    100      100        100      100

In [28]:
df.loc[9, 'chemistry']

100

In [29]:
df.loc[9, 'chemistry'] = 90

In [30]:
df.loc[9, 'biology'] = 87

In [31]:
df

   roll        name  maths  Physics  chemistry  biology
0     1  Ajay Kumar     78       78         78       78
1     2        Amit     56        5         56       56
2     3        Arun     98        8         98       98
3     4      Anisha      5       35         95       57
4     5       Abhay      4       74         74       46
5     6         Ram      5       75         45       55
6     7        Sham      7       87         77       47
7     8      Prince      9       89         49       39
8     9       Jatin      8       38         48       28
9    10    Arshnoor    100      100         90       87

### Adding a New Column

In [32]:
fathername = ['a','b','c','d','e','f','g','h','i','j']

In [33]:
df['fathername'] = fathername

In [34]:
df

   roll        name  maths  Physics  chemistry  biology fathername
0     1  Ajay Kumar     78       78         78       78          a
1     2        Amit     56        5         56       56          b
2     3        Arun     98        8         98       98          c
3     4      Anisha      5       35         95       57          d
4     5       Abhay      4       74         74       46          e
5     6         Ram      5       75         45       55          f
6     7        Sham      7       87         77       47          g
7     8      Prince      9       89         49       39          h
8     9       Jatin      8       38         48       28          i
9    10    Arshnoor    100      100         90       87          j

### insert function

In [36]:
df.insert(2, 'fathername1', fathername)

In [37]:
df

   roll        name fathername1  maths  Physics  chemistry  biology fathername
0     1  Ajay Kumar           a     78       78         78       78          a
1     2        Amit           b     56        5         56       56          b
2     3        Arun           c     98        8         98       98          c
3     4      Anisha           d      5       35         95       57          d
4     5       Abhay           e      4       74         74       46          e
5     6         Ram           f      5       75         45       55          f
6     7        Sham           g      7       87         77       47          g
7     8      Prince           h      9       89         49       39          h
8     9       Jatin           i      8       38         48       28          i
9    10    Arshnoor           j    100      100         90       87          j

### Removing a Column from dataframe

#### pop function

In [38]:
df.pop('fathername')

0    a
1    b
2    c
3    d
4    e
5    f
6    g
7    h
8    i
9    j
Name: fathername, dtype: object

In [39]:
df

   roll        name fathername1  maths  Physics  chemistry  biology
0     1  Ajay Kumar           a     78       78         78       78
1     2        Amit           b     56        5         56       56
2     3        Arun           c     98        8         98       98
3     4      Anisha           d      5       35         95       57
4     5       Abhay           e      4       74         74       46
5     6         Ram           f      5       75         45       55
6     7        Sham           g      7       87         77       47
7     8      Prince           h      9       89         49       39
8     9       Jatin           i      8       38         48       28
9    10    Arshnoor           j    100      100         90       87

#### other functions

In [40]:
df.index[5]

5

### drop function

In [41]:
df.drop(3) #Deleting a row from DataFrame

   roll        name fathername1  maths  Physics  chemistry  biology
0     1  Ajay Kumar           a     78       78         78       78
1     2        Amit           b     56        5         56       56
2     3        Arun           c     98        8         98       98
4     5       Abhay           e      4       74         74       46
5     6         Ram           f      5       75         45       55
6     7        Sham           g      7       87         77       47
7     8      Prince           h      9       89         49       39
8     9       Jatin           i      8       38         48       28
9    10    Arshnoor           j    100      100         90       87

In [42]:
df.drop(df.index[3])

   roll        name fathername1  maths  Physics  chemistry  biology
0     1  Ajay Kumar           a     78       78         78       78
1     2        Amit           b     56        5         56       56
2     3        Arun           c     98        8         98       98
4     5       Abhay           e      4       74         74       46
5     6         Ram           f      5       75         45       55
6     7        Sham           g      7       87         77       47
7     8      Prince           h      9       89         49       39
8     9       Jatin           i      8       38         48       28
9    10    Arshnoor           j    100      100         90       87

In [44]:
df.drop('fathername1', axis=1) # deleting a column from DataFrame

   roll        name  maths  Physics  chemistry  biology
0     1  Ajay Kumar     78       78         78       78
1     2        Amit     56        5         56       56
2     3        Arun     98        8         98       98
3     4      Anisha      5       35         95       57
4     5       Abhay      4       74         74       46
5     6         Ram      5       75         45       55
6     7        Sham      7       87         77       47
7     8      Prince      9       89         49       39
8     9       Jatin      8       38         48       28
9    10    Arshnoor    100      100         90       87

### String Filters

In [45]:
df[df['name'].str.contains('am')]

   roll  name fathername1  maths  Physics  chemistry  biology
5     6   Ram           f      5       75         45       55
6     7  Sham           g      7       87         77       47

In [46]:
df[df['name'].str.contains('A')]

   roll        name fathername1  maths  Physics  chemistry  biology
0     1  Ajay Kumar           a     78       78         78       78
1     2        Amit           b     56        5         56       56
2     3        Arun           c     98        8         98       98
3     4      Anisha           d      5       35         95       57
4     5       Abhay           e      4       74         74       46
9    10    Arshnoor           j    100      100         90       87

In [47]:
df[df['name'].str.contains('a')]

   roll        name fathername1  maths  Physics  chemistry  biology
0     1  Ajay Kumar           a     78       78         78       78
3     4      Anisha           d      5       35         95       57
4     5       Abhay           e      4       74         74       46
5     6         Ram           f      5       75         45       55
6     7        Sham           g      7       87         77       47
8     9       Jatin           i      8       38         48       28

In [49]:
df[df['name'].str.startswith('S')]

   roll  name fathername1  maths  Physics  chemistry  biology
6     7  Sham           g      7       87         77       47

In [51]:
df[df['name'].str.endswith('r')]

   roll        name fathername1  maths  Physics  chemistry  biology
0     1  Ajay Kumar           a     78       78         78       78
9    10    Arshnoor           j    100      100         90       87