In [1]:
import pandas as pd

In [2]:
d = {
    'roll':[1,2,3,4,5,6,7,8,9,10],
    'name':['Ajay', 'Amit', 'Arun','Anisha', 'Abhay', 'Ram', 'Sham', 'Prince', 'Jatin', 'Arshnoor'],
    'maths':[78,56,98,5,4,5,7,9,8,100],
    'Physics':[78,5,8,35,74,75,87,89,38,100],
    'chemistry':[78,56,98,95,74,45,77,49,48,100],
    'biology':[78,56,98,57,46,55,47,39,28,100]
}
df = pd.DataFrame(d)
df

   roll      name  maths  Physics  chemistry  biology
0     1      Ajay     78       78         78       78
1     2      Amit     56        5         56       56
2     3      Arun     98        8         98       98
3     4    Anisha      5       35         95       57
4     5     Abhay      4       74         74       46
5     6       Ram      5       75         45       55
6     7      Sham      7       87         77       47
7     8    Prince      9       89         49       39
8     9     Jatin      8       38         48       28
9    10  Arshnoor    100      100        100      100

In [3]:
f1 = df['maths'] > 90
f2 = df['Physics'] > 90

In [4]:
print(f1)
print(f2)

0    False
1    False
2     True
3    False
4    False
5    False
6    False
7    False
8    False
9     True
Name: maths, dtype: bool
0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9     True
Name: Physics, dtype: bool

In [5]:
df[f1][f2]

C:\Users\arshn\AppData\Local\Temp\ipykernel_24764\1445824473.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[f1][f2]

   roll      name  maths  Physics  chemistry  biology
9    10  Arshnoor    100      100        100      100

In [6]:
df[f1&f2]  # and operation

   roll      name  maths  Physics  chemistry  biology
9    10  Arshnoor    100      100        100      100

In [7]:
df[f1|f2] #or operation

   roll      name  maths  Physics  chemistry  biology
2     3      Arun     98        8         98       98
9    10  Arshnoor    100      100        100      100

In [8]:
df[f2]

   roll      name  maths  Physics  chemistry  biology
9    10  Arshnoor    100      100        100      100

In [9]:
df[~f2]

   roll    name  maths  Physics  chemistry  biology
0     1    Ajay     78       78         78       78
1     2    Amit     56        5         56       56
2     3    Arun     98        8         98       98
3     4  Anisha      5       35         95       57
4     5   Abhay      4       74         74       46
5     6     Ram      5       75         45       55
6     7    Sham      7       87         77       47
7     8  Prince      9       89         49       39
8     9   Jatin      8       38         48       28

In [10]:
# WAP to print the roll no of students who have scored marks greater than 85 in either of these subjects
#maths, chemistry, biology

In [13]:
f3 = df['maths'] > 85
f4 = df['chemistry'] > 85
f5 = df['biology'] > 85
df['roll'][f3|f4|f5]

2     3
3     4
9    10
Name: roll, dtype: int64

In [15]:
df['roll'][df['maths'] > 85]

2     3
9    10
Name: roll, dtype: int64

In [16]:
# WAP to print %age of following students Amit Abhay Jatin

In [18]:
f6 = df['name'] == 'Amit'
f7 = df['name'] == 'Abhay'
f8 = df['name'] == 'Jatin'

In [28]:
f9 = f6|f7|f8

In [29]:
df['total'] = df['maths'] + df['Physics'] + df['chemistry'] + df['biology']
df['percentage'] = df['total'] / 400 * 100

In [30]:
df[['roll','name','percentage']][f9]

   roll   name  percentage
1     2   Amit       43.25
4     5  Abhay       49.50
8     9  Jatin       30.50

In [31]:
f7 = df['name'].isin(['Amit', 'Abhay', 'Arshnoor'])
f7

0    False
1     True
2    False
3    False
4     True
5    False
6    False
7    False
8    False
9     True
Name: name, dtype: bool

In [32]:
df[['name','roll','percentage']][f7]

       name  roll  percentage
1      Amit     2       43.25
4     Abhay     5       49.50
9  Arshnoor    10      100.00

In [33]:
df[['name','roll','percentage']][df['name'].isin(['Amit', 'Abhay', 'Arshnoor'])]

       name  roll  percentage
1      Amit     2       43.25
4     Abhay     5       49.50
9  Arshnoor    10      100.00

In [34]:
#To print 'name','roll','percentage 1 to 7 using rollno.

In [40]:
list1 = ['name','roll','percentage']
for i in range(1,8):
    print(df[list1][df['roll'].isin([f'{i}'])])

Empty DataFrame
Columns: [name, roll, percentage]
Index: []
Empty DataFrame
Columns: [name, roll, percentage]
Index: []
Empty DataFrame
Columns: [name, roll, percentage]
Index: []
Empty DataFrame
Columns: [name, roll, percentage]
Index: []
Empty DataFrame
Columns: [name, roll, percentage]
Index: []
Empty DataFrame
Columns: [name, roll, percentage]
Index: []
Empty DataFrame
Columns: [name, roll, percentage]
Index: []

In [39]:
df[list1][df['roll'].isin([1,2,3,4,5,6,7])]

     name  roll  percentage
0    Ajay     1       78.00
1    Amit     2       43.25
2    Arun     3       75.50
3  Anisha     4       48.00
4   Abhay     5       49.50
5     Ram     6       45.00
6    Sham     7       54.50

In [42]:
df.nsmallest(4, 'maths')  #df.nsmallest(no. of rows,'column name')

   roll    name  maths  Physics  chemistry  biology  total  percentage
4     5   Abhay      4       74         74       46    198        49.5
3     4  Anisha      5       35         95       57    192        48.0
5     6     Ram      5       75         45       55    180        45.0
6     7    Sham      7       87         77       47    218        54.5

In [43]:
df.nsmallest(3, 'total')

   roll   name  maths  Physics  chemistry  biology  total  percentage
8     9  Jatin      8       38         48       28    122       30.50
1     2   Amit     56        5         56       56    173       43.25
5     6    Ram      5       75         45       55    180       45.00

In [44]:
df[['roll', 'name', 'total']].nsmallest(3, 'total')

   roll   name  total
8     9  Jatin    122
1     2   Amit    173
5     6    Ram    180

In [45]:
df.nlargest(3, 'total')

   roll      name  maths  Physics  chemistry  biology  total  percentage
9    10  Arshnoor    100      100        100      100    400       100.0
0     1      Ajay     78       78         78       78    312        78.0
2     3      Arun     98        8         98       98    302        75.5

In [46]:
df[['roll', 'name', 'total']].nlargest(3, 'total')

   roll      name  total
9    10  Arshnoor    400
0     1      Ajay    312
2     3      Arun    302