In [1]:
import pandas
import numpy

In [4]:
arr2d = numpy.array([[1,2,3,4],[5,6,7,8]])
arr2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
arr2d.shape

(2, 4)

In [6]:
df = pandas.DataFrame([1,2,3,4,5])
print(df)

   0
0  1
1  2
2  3
3  4
4  5

In [7]:
df1 = pandas.DataFrame([[1,2,3,4,5],[6,7,8,9,0]])
print(df1)

   0  1  2  3  4
0  1  2  3  4  5
1  6  7  8  9  0

In [9]:
df2 = pandas.DataFrame([[1,2,3,4,5],[6,7,8,9,0]], index=['a','b'])
print(df2)

   0  1  2  3  4
a  1  2  3  4  5
b  6  7  8  9  0

In [10]:
df3 = pandas.DataFrame([[1,2,3,4,5],[6,7,8,9,0]], index=['a','b'], columns=['a','b','c','d','e'])
print(df3)

   a  b  c  d  e
a  1  2  3  4  5
b  6  7  8  9  0

In [11]:
df3

   a  b  c  d  e
a  1  2  3  4  5
b  6  7  8  9  0

### Creating DataFrame using Dictionary

In [12]:
d = {
    'rollno':[1,2,3,4,5],
    'name':['Aman', 'Ajay', 'Arshnoor', 'Jatin', 'Vasu'],
    'class':['BCA', 'BCA', 'Btech', 'MCA', 'BCA']
}
df4 = pandas.DataFrame(d)
df4

   rollno      name  class
0       1      Aman    BCA
1       2      Ajay    BCA
2       3  Arshnoor  Btech
3       4     Jatin    MCA
4       5      Vasu    BCA

In [13]:
print(df4)

   rollno      name  class
0       1      Aman    BCA
1       2      Ajay    BCA
2       3  Arshnoor  Btech
3       4     Jatin    MCA
4       5      Vasu    BCA

#### CSV -> Comma Separated Values

In [15]:
df = pandas.read_csv("C:\\Users\\vmmin\\Desktop\\students.csv")
df

   roll     name class  marks
0     1    rahul   bca     56
1     1    vikas   bca     54
2     1     vasu   bca     76
3     1     ajay   bca     89
4     1  avinoor   bca     65
5     1    jatin   bca     90
6     1    vijay   bca     45
7     1     amit   bca     23
8     1   gaurav   bca     78

In [19]:
df1 = pandas.read_excel("C:\\Users\\vmmin\\Desktop\\students.xlsx")
df1

   roll     name class  marks
0     1    rahul   bca     56
1     1    vikas   bca     54
2     1     vasu   bca     76
3     1     ajay   bca     89
4     1  avinoor   bca     65
5     1    jatin   bca     90
6     1    vijay   bca     45
7     1     amit   bca     23
8     1   gaurav   bca     78

In [20]:
df['name']

0      rahul
1      vikas
2       vasu
3       ajay
4    avinoor
5      jatin
6      vijay
7       amit
8     gaurav
Name: name, dtype: object

In [21]:
df.name

0      rahul
1      vikas
2       vasu
3       ajay
4    avinoor
5      jatin
6      vijay
7       amit
8     gaurav
Name: name, dtype: object

In [22]:
df.to_csv('D://new_students.csv')

In [23]:
df.to_excel('D://new_students23.xlsx')

In [24]:
df.to_clipboard()

In [25]:
df.to_clipboard(sep=',')

In [28]:
df.to_dict()

{'roll': {0: 1, 1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1},
 'name': {0: 'rahul',
  1: 'vikas',
  2: 'vasu',
  3: 'ajay',
  4: 'avinoor',
  5: 'jatin',
  6: 'vijay',
  7: 'amit',
  8: 'gaurav'},
 'class': {0: 'bca',
  1: 'bca',
  2: 'bca',
  3: 'bca',
  4: 'bca',
  5: 'bca',
  6: 'bca',
  7: 'bca',
  8: 'bca'},
 'marks': {0: 56, 1: 54, 2: 76, 3: 89, 4: 65, 5: 90, 6: 45, 7: 23, 8: 78}}

In [30]:
df = pandas.read_csv('bollywood.csv')
df

,Year,Title,Director,Cast,Genre,Release Month,Release Date,Highest Grosser By Year(in crores)
0,1920,Balika Badhu a.k.a. Baby Bride,P. T. Shaida (Tulsidutt Shaida),"shaida,pandit,ali,miss,tarak,bagcha,tulsidutt",social,NaN,NaN,NaN
1,1920,Daksha Yagna a.k.a. Sati Parvati,Vishnupant Divekar,"prabha,khalil,vaidya",mythology,NaN,NaN,NaN
2,1920,Jalandhar Vrinda a.k.a. Sati Tulsi Vrinda,G. V. Sane,unknown,mythology,NaN,NaN,NaN
3,1920,Kansa Vadha a.k.a. End Of The Tyrant King,G. V. Sane,unknown,mythology,NaN,NaN,NaN
4,1920,Katorabhar Khoon a.k.a.The Stinger Stung a.k.a...,S. N. Patankar,"koregaonkar,gokhale,vyas,trymbakrao,pradhan,ta...",social,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
9677,2019,Panipat,Ashutosh Gowariker,Sanjay DuttArjun KapoorKriti SanonKabir Bedi,Action/battle,DEC,6.0,NaN
9678,2019,"Pati, Patni Aur Woh",Mudassar Aziz,Kartik AaryanBhumi PednekarAnanya Panday,Comedy,DEC,6.0,NaN
9679,2019,Mardaani 2,Gopi Puthran,Rani MukherjeeVikram Singh ChauhanShruti Bapna...,Crime Thriller,DEC,13.0,NaN
9680,2019,Dabangg 3,Prabhu Deva,Salman KhanSonakshi SinhaArbaaz KhanMahie Gill...,Action,DEC,20.0,NaN
9681,2019,Good News,Raj Mehta,Akshay KumarKareena KapoorDiljit DosanjhKiara ...,Comedy,DEC,27.0,NaN

In [31]:
df.head()

,Year,Title,Director,Cast,Genre,Release Month,Release Date,Highest Grosser By Year(in crores)
0,1920,Balika Badhu a.k.a. Baby Bride,P. T. Shaida (Tulsidutt Shaida),"shaida,pandit,ali,miss,tarak,bagcha,tulsidutt",social,NaN,NaN,NaN
1,1920,Daksha Yagna a.k.a. Sati Parvati,Vishnupant Divekar,"prabha,khalil,vaidya",mythology,NaN,NaN,NaN
2,1920,Jalandhar Vrinda a.k.a. Sati Tulsi Vrinda,G. V. Sane,unknown,mythology,NaN,NaN,NaN
3,1920,Kansa Vadha a.k.a. End Of The Tyrant King,G. V. Sane,unknown,mythology,NaN,NaN,NaN
4,1920,Katorabhar Khoon a.k.a.The Stinger Stung a.k.a...,S. N. Patankar,"koregaonkar,gokhale,vyas,trymbakrao,pradhan,ta...",social,NaN,NaN,NaN

In [32]:
df.head(3)

,Year,Title,Director,Cast,Genre,Release Month,Release Date,Highest Grosser By Year(in crores)
0,1920,Balika Badhu a.k.a. Baby Bride,P. T. Shaida (Tulsidutt Shaida),"shaida,pandit,ali,miss,tarak,bagcha,tulsidutt",social,NaN,NaN,NaN
1,1920,Daksha Yagna a.k.a. Sati Parvati,Vishnupant Divekar,"prabha,khalil,vaidya",mythology,NaN,NaN,NaN
2,1920,Jalandhar Vrinda a.k.a. Sati Tulsi Vrinda,G. V. Sane,unknown,mythology,NaN,NaN,NaN

In [33]:
df.head(9)

,Year,Title,Director,Cast,Genre,Release Month,Release Date,Highest Grosser By Year(in crores)
0,1920,Balika Badhu a.k.a. Baby Bride,P. T. Shaida (Tulsidutt Shaida),"shaida,pandit,ali,miss,tarak,bagcha,tulsidutt",social,NaN,NaN,NaN
1,1920,Daksha Yagna a.k.a. Sati Parvati,Vishnupant Divekar,"prabha,khalil,vaidya",mythology,NaN,NaN,NaN
2,1920,Jalandhar Vrinda a.k.a. Sati Tulsi Vrinda,G. V. Sane,unknown,mythology,NaN,NaN,NaN
3,1920,Kansa Vadha a.k.a. End Of The Tyrant King,G. V. Sane,unknown,mythology,NaN,NaN,NaN
4,1920,Katorabhar Khoon a.k.a.The Stinger Stung a.k.a...,S. N. Patankar,"koregaonkar,gokhale,vyas,trymbakrao,pradhan,ta...",social,NaN,NaN,NaN
5,1920,Krishna Sudama a.k.a. Shri Krishna Sudama,Vishnupant Divekar,"sakina,ali,moti,prabha,khalil,kesarbai,miya,va...",mythology,NaN,NaN,NaN
6,1920,Lava Kusha,R. Nataraja Mudaliar,unknown,mythology,NaN,NaN,NaN
7,1920,Mahabharata,Rustomji Dhotiwala,unknown,unknown,NaN,NaN,NaN
8,1920,Mrichhakatik,Suchet Singh,"kanjibhai,rathod",unknown,NaN,NaN,NaN

In [34]:
df.tail()

,Year,Title,Director,Cast,Genre,Release Month,Release Date,Highest Grosser By Year(in crores)
9677,2019,Panipat,Ashutosh Gowariker,Sanjay DuttArjun KapoorKriti SanonKabir Bedi,Action/battle,DEC,6.0,NaN
9678,2019,"Pati, Patni Aur Woh",Mudassar Aziz,Kartik AaryanBhumi PednekarAnanya Panday,Comedy,DEC,6.0,NaN
9679,2019,Mardaani 2,Gopi Puthran,Rani MukherjeeVikram Singh ChauhanShruti Bapna...,Crime Thriller,DEC,13.0,NaN
9680,2019,Dabangg 3,Prabhu Deva,Salman KhanSonakshi SinhaArbaaz KhanMahie Gill...,Action,DEC,20.0,NaN
9681,2019,Good News,Raj Mehta,Akshay KumarKareena KapoorDiljit DosanjhKiara ...,Comedy,DEC,27.0,NaN

In [35]:
df.tail(8)

,Year,Title,Director,Cast,Genre,Release Month,Release Date,Highest Grosser By Year(in crores)
9674,2019,Pagalpanti,Anees Bazmee,Anil KapoorJohn AbrahamIleana D'CruzArshad War...,Comedy,NOV,22.0,NaN
9675,2019,Dil Bechara,Mukesh Chhabra,Sushant Singh RajputSanjana SanghiSaif Ali Khan,Romantic drama,NOV,29.0,NaN
9676,2019,Jawaani Jaaneman,Nitin Kakkar,Saif Ali KhanTabuAlaia Furniturewalla,Romantic drama,NOV,29.0,NaN
9677,2019,Panipat,Ashutosh Gowariker,Sanjay DuttArjun KapoorKriti SanonKabir Bedi,Action/battle,DEC,6.0,NaN
9678,2019,"Pati, Patni Aur Woh",Mudassar Aziz,Kartik AaryanBhumi PednekarAnanya Panday,Comedy,DEC,6.0,NaN
9679,2019,Mardaani 2,Gopi Puthran,Rani MukherjeeVikram Singh ChauhanShruti Bapna...,Crime Thriller,DEC,13.0,NaN
9680,2019,Dabangg 3,Prabhu Deva,Salman KhanSonakshi SinhaArbaaz KhanMahie Gill...,Action,DEC,20.0,NaN
9681,2019,Good News,Raj Mehta,Akshay KumarKareena KapoorDiljit DosanjhKiara ...,Comedy,DEC,27.0,NaN